---
title: "#endthelockdown"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rtweet)
library(httpuv)
```

```{r}
token <-
  create_token(
    app = "endthelockdown Research",
    consumer_key    = Sys.getenv("api_key"),
    consumer_secret = Sys.getenv("api_secret_key"),
    access_token    = Sys.getenv("access_token"),
    access_secret   = Sys.getenv("access_secret")
  )
```


```{r}
lockdown_tweets <- 
  search_tweets("EndTheShutdown",
                n = 100000,
                include_rts = F,
                # geocode = "39.00, -75.50, 75mi",
                retryonratelimit = T,
                token = token)
```

```{r}
lockdown_tweets %>% 
  select(user_id, status_id, created_at, screen_name, text, source,
         reply_to_status_id, reply_to_user_id, reply_to_screen_name,
         is_quote, is_retweet, favorite_count, retweet_count, quote_count,
         reply_count, lang, quoted_status_id, quoted_text, quoted_created_at, 
         quoted_source, quoted_favorite_count, quoted_retweet_count,
         quoted_user_id, quoted_screen_name, quoted_name, quoted_followers_count,
         quoted_friends_count, quoted_statuses_count, quoted_location,
         quoted_description, quoted_verified, retweet_status_id, retweet_text,
         retweet_created_at, retweet_source, retweet_favorite_count,
         retweet_retweet_count, retweet_user_id, retweet_screen_name,
         retweet_name, retweet_followers_count, retweet_friends_count,
         retweet_statuses_count, retweet_location, retweet_description,
         retweet_verified, place_url, place_name, place_full_name,
         place_type, country, country_code, status_url, name, location,
         description, url, protected, followers_count, friends_count,
         listed_count, statuses_count, favourites_count, account_created_at,
         verified, profile_url, profile_expanded_url, account_lang, 
         profile_banner_url, profile_background_url, profile_image_url) %>% 
  write_csv(here::here("Data", 
                       glue::glue("{Sys.time()}_lockdown_tweets.csv")))
```









